name: Laurenceshorter
favicon: null
layout_spectrum: 0.2729013906791806
typography_spectrum: 0.28905529086478055
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5968352153431624
  lightness: 0.9654421345330775
  saturation: 0.026525653200224042
  rhythmicContrast: 0.4171734778210521
purpose: []
