name: Laurenceshorter
favicon: null
layout_spectrum: 0.99414
typography_spectrum: 0.28905529086478055
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffe66b'
    - '#ff5f00'
    - '#7ad4b4'
    - '#0a0000'
    - '#a3a494'
  brandStrength: 0.625
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
